version: "3.8"

services:
  backend:
    image: megapz/vivamq-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  ai-processor:
    image: megapz/vivamq-ai-processor:latest
    build:
      context: ./ai-processor
      dockerfile: Dockerfile

  frontend:
    image: megapz/vivamq-frontend:latest
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started