services:
  backend:
    image: megapz/vivamq-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  ai-processor:
    image: megapz/vivamq-ai-processor:latest
    build:
      context: ./ai-processor
      dockerfile: Dockerfile
    env_file:
      - ./.env

  frontend:
    image: megapz/vivamq-frontend:latest
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env