services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:example@mysql:3306/vivamq
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - mysql
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vivamq
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  ai-processor:
    build:
      context: ./ai-processor
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./ai-processor/.env
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq

volumes:
  mysql-data:
