name: Build and Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup SSH for connecting to the DigitalOcean Droplet
      - name: Setup SSH for DigitalOcean
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          mkdir -p ~/.ssh # Create the .ssh directory if it doesn't exist
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 4: Build and push Docker images using Compose
      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

      # Step 5: Zip the repository
      - name: Zip repository
        run: zip -r repo.zip .

      # Step 6: Copy the zipped repository to the remote system
      - name: Copy zipped repository to remote
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          scp -o StrictHostKeyChecking=no repo.zip $DROPLET_USER@$DROPLET_IP:~/

      # Step 7: Deploy the updated container images to the DigitalOcean Droplet
      - name: Deploy to DigitalOcean Droplet
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          ssh $DROPLET_USER@$DROPLET_IP << 'EOF'
            chmod 600 ~/repo.zip
            unzip ~/repo.zip -d ~/
            cd ~
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
          EOF
